import axios from "axios";

const fake = [
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 18,
    createdAt: "2022-04-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "6137de1b1c73eb28103c1780",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "6137df651c73eb28103c19a4",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "BZ",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "BZ",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "14",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "advertiser",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
];

const getAllAnnonceurs = (dispatch, state) => {
  try {
    if (state.isRealData) {
      axios.get("http://41.231.54.51/server/advertiser").then((res) => {
        dispatch({
          type: "annoceursList",
          annonceurs: res.data.list,
          isRealData: true,
        });
      });
    } else {
      dispatch({ type: "annoceursList", annonceurs: fake, isRealData: false });
    }
  } catch (error) {
    dispatch({ type: "annoceursList", annonceurs: [], isRealData: false });
  }
};

export const annonceurAction = {
  getAllAnnonceurs,
};
