import axios from "axios";

const fake = [
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
  {
    id: "string",
    firstName: "string",
    lastName: "string",
    email: "string",
    emailPerso: "string",
    role: "searcher",
    status: 0,
    nationalite: "string",
    username: "string",
    voluntary: true,
    farmNb: 0,
    createdAt: "2022-05-05T10:20:27.897Z",
    verifed: true,
    subscriptionNb: 0,
    govId: "string",
    delegationId: "string",
    localityId: "string",
    ageId: "string",
  },
];
const getAllSearcher = (dispatch, state) => {
  try {
    if (state.isRealData) {
      axios.get("http://41.231.54.51/server/searcher").then((res) => {
        dispatch({ type: "chercheursList", chercheurs: res.data.list });
      });
    } else {
      dispatch({ type: "chercheursList", chercheurs: fake });
    }
  } catch (error) {
    console.log(error);
  }
};

export const searcherAction = {
  getAllSearcher,
};
